apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-example-app
  labels:
    app: prometheus-example-app
  namespace: servicemonitor-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-example-app
  template:
    metadata:
      labels:
        app: prometheus-example-app
    spec:
      containers:
      - name: prometheus-example-app
        image: axodevelopment/servicemonitor:v1.0.0.4
        ports:
        - containerPort: 8080
        imagePullPolicy: Always