apiVersion: v1
kind: Service
metadata:
  name: prometheus-example-app
  namespace: servicemonitor-a
  labels:
    app: prometheus-example-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: web
  selector:
    app: prometheus-example-app
  type: ClusterIP
